site_name: Data Pipes by Actio
theme: 'material'

markdown_extensions:
  - codehilite
  - admonition

pages:
    - Home: index.md
    - PipeScript®:
      - Introduction: configuration.md
      - Tasks: tasks.md
      - Data Sources: datasources.md
      - Pipelines: pipelines.md
    - Command Line: commandline.md
    - Data Sets: datasets.md
    - Expressions:
      - Selection: selection.md
      - Operators: operators.md
      - Data Set Functions: dataset_functions.md
      - Utility Functions: functions.md
      - Conditionals: conditionals.md
      - Higher Order Functions: higher_order_functions.md
    - Templates: templates.md
    - Data Sources: 
      - Introduction: datasources.md
      - Files: datasource_file.md
      - FTP: datasource_ftp.md
      - JDBC: datasource_jdbc.md
      - REST: datasource_rest.md